### ISSUE TITLE
How should the YieldSource handle yield bearing tokens

### ISSUE THREAD

**Issue by steffenix** [pooltogether/pooltogether-pool-contracts#278]
I am looking at:

```
  function _supply(uint256 mintAmount) internal override {
    yieldSource.token().approve(address(yieldSource), mintAmount);
    yieldSource.supplyTo(mintAmount, address(this));
  }

  /// @notice Redeems asset tokens from the yield source.
  /// @param redeemAmount The amount of yield-bearing tokens to be redeemed
  /// @return The actual amount of tokens that were redeemed.
  function _redeem(uint256 redeemAmount) internal override returns (uint256) {
    return yieldSource.redeem(redeemAmount);
  }
}
```
We can see that the yield baring tokens that have been minted are attributed back to the pool, at first I thought that's a transfer back to the pool but if that's the case, It seems it's missing a` transfer `to transfer back the yield bearing token to the yieldSource.

====

An other way is to have the yieldBearingToken holding the yield bearing token and keeps track of the different deposit with like an ERC20 if that's the idea I think it should be specified in the interface file.

====

I am also confused on how the amount of yield bearing token of an address will be calculated.

**Comment by asselstine** [comment]
> It seems it's missing a `transfer` to transfer back the yield bearing token to the yieldSource.

Not sure I follow you here; the yield source just takes a token and accrues yield for its users.  In your case, the `token()` will be $SUSHI.  When users deposit SUSHI into the Prize Pool it will then go and deposit SUSHI into the Yield Source.  The yield source will hold xSUSHI, and can track balances of xSUSHI for each depositor.

If you'd like to see an example, you can have a look at the [CTokenYieldSource](https://github.com/pooltogether/pooltogether-pool-contracts/blob/dbb70a7ba71a5d75f615bdd8f989ed6925e46595/contracts/yield-source/CTokenYieldSource.sol#L61).  The CTokenYieldSource wraps a Compound cToken.  For example, if it's cDai, then the `token()` would be Dai.  The CTokenYieldSource tracks the cDai held by each depositor, and is able to calculate their balance as the value of the cDai increases.

> I am also confused on how the amount of yield bearing token of an address will be calculated.

The YieldSourceInterface [balanceOf](https://github.com/pooltogether/pooltogether-pool-contracts/blob/dbb70a7ba71a5d75f615bdd8f989ed6925e46595/contracts/yield-source/CTokenYieldSource.sol#L47) method should always increase; like an Aave aToken.

**Comment by steffenix** [comment]
Understood
